In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('drug200.csv')

In [3]:
print(data['Sex'].unique())
print(data['BP'].unique())
print(data['Cholesterol'].unique())
print(data['Drug'].unique())

['F' 'M']
['HIGH' 'LOW' 'NORMAL']
['HIGH' 'NORMAL']
['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']


In [4]:
data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

#data['Sex'] = label_encoder.fit_transform(data['Sex'])
#data['Sex']

categorical_data = ['Sex', 'BP', 'Cholesterol', 'Drug']

for i in categorical_data:
    print(data[i].unique())
    data[i] = label_encoder.fit_transform(data[i])
    print(data[i].unique())

['F' 'M']
[0 1]
['HIGH' 'LOW' 'NORMAL']
[0 1 2]
['HIGH' 'NORMAL']
[0 1]
['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']
[0 3 4 1 2]


In [6]:
data

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     0
1     47    1   1            0   13.093     3
2     47    1   1            0   10.114     3
3     28    0   2            0    7.798     4
4     61    0   1            0   18.043     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     3
196   16    1   1            0   12.006     3
197   52    1   2            0    9.894     4
198   23    1   2            1   14.020     4
199   40    0   1            1   11.349     4

[200 rows x 6 columns]

In [7]:
x = data.drop(['Drug'], axis=1)
y = data['Drug']
y

0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int32

In [8]:
#Train test split 
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, 
                                                    random_state = 0)

In [9]:
#lihat jumlah data train & testing 
print(x_train.shape)
print(y_test.shape)

(150, 5)
(50,)


In [10]:
from sklearn.naive_bayes import GaussianNB 

model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [11]:
#pemodelan training
y_pred = model.predict(x_train)
y_pred
print(y_pred)

y_pred_test = model.predict(x_test)
print(y_pred_test)

[0 2 0 0 3 0 4 4 0 2 0 0 4 0 0 0 2 0 4 4 4 0 1 1 1 0 0 4 4 0 1 1 2 3 2 0 3
 1 2 4 4 3 0 0 3 0 2 2 0 4 3 1 0 0 3 1 4 2 4 2 0 0 0 2 0 2 3 2 4 0 1 1 0 0
 1 1 4 4 1 4 0 0 3 1 3 4 1 1 4 1 0 3 4 0 0 3 0 4 4 4 4 0 1 4 0 1 0 0 4 0 4
 2 2 0 4 1 4 2 1 1 3 1 3 4 1 4 3 4 1 1 3 4 0 1 0 4 4 1 0 2 3 1 0 0 4 4 3 4
 3 0]
[3 4 0 0 0 4 4 4 3 4 1 0 0 0 2 3 0 0 4 1 1 4 4 4 0 0 0 0 0 4 4 3 1 4 0 0 4
 3 1 4 0 1 0 0 0 4 4 0 1 2]


In [12]:
# y pred vs y actual

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_pred, y_train))

print(classification_report(y_pred, y_train))

[[46  0  0  0  1]
 [11 18  0  0  0]
 [ 2  0 15  0  0]
 [ 6  0  0 13  0]
 [ 1  0  0  0 37]]
              precision    recall  f1-score   support

           0       0.70      0.98      0.81        47
           1       1.00      0.62      0.77        29
           2       1.00      0.88      0.94        17
           3       1.00      0.68      0.81        19
           4       0.97      0.97      0.97        38

    accuracy                           0.86       150
   macro avg       0.93      0.83      0.86       150
weighted avg       0.90      0.86      0.86       150



In [13]:
#0.86 = 86% menandakan akurasi prediksi sebesar 86% dari data aslinya