In [42]:
#import library python
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [43]:
dataset = pd.read_csv("InternetSpeed22.csv")

In [52]:
print(data['country'].unique())
print(data['broadband'].unique())
print(data['mobile'].unique())

['Monaco' 'Singapore' 'Hong Kong' 'Romania' 'Switzerland' 'Denmark'
 'Thailand' 'Chile' 'France' 'South Korea' 'Hungary' 'Liechtenstein'
 'United States' 'Spain' 'China' 'United Arab Emirates' 'Canada' 'Macau'
 'Japan' 'Sweden' 'Luxembourg' 'Andorra' 'New Zealand' 'Norway'
 'Netherlands' 'Israel' 'Portugal' 'Poland' 'Moldova' 'Taiwan' 'Kuwait'
 'Lithuania' 'Malta' 'Panama' 'Germany' 'Latvia' 'Finland' 'Belgium'
 'Ireland' 'San Marino' 'Slovenia' 'Slovakia' 'Qatar' 'Brazil' 'Barbados'
 'Malaysia' 'Italy' 'United Kingdom' 'Russia' 'Saudi Arabia' 'Austria'
 'Estonia' 'Serbia' 'Bulgaria' 'Trinidad and Tobago' 'Jordan' 'Australia'
 'Vietnam' 'Ukraine' 'Bahrain' 'Paraguay' 'Colombia' 'Philippines'
 'Uruguay' 'Belarus' 'Croatia' 'Oman' 'Guyana' 'India' 'Kazakhstan'
 'Bahamas' 'Montenegro' 'Argentina' 'Peru' 'Grenada' 'Costa Rica' 'Cyprus'
 'Mexico' 'South Africa' 'Saint Vincent and the Grenadines' 'Mongolia'
 'Saint Lucia' 'Ghana' 'Kyrgyzstan' 'Bosnia and Herzegovina' 'Laos'
 'Uzbekistan' 'Al

In [53]:
dataset.describe()

broadband      mobile
count  177.000000  136.000000
mean    72.672825   53.788235
std     66.461751   43.327121
min      4.010000    7.270000
25%     22.500000   24.402500
50%     43.480000   35.825000
75%    109.410000   69.205000
max    261.820000  238.060000

In [54]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

#data['country'] = label_encoder.fit_transform(data['country'])
#data['country']

categorical_dataset = ['country', 'broadband', 'mobile']

for i in categorical_dataset:
    print(dataset[i].unique())
    dataset[i] = label_encoder.fit_transform(dataset[i])
    print(dataset[i].unique())

['Monaco' 'Singapore' 'Hong Kong' 'Romania' 'Switzerland' 'Denmark'
 'Thailand' 'Chile' 'France' 'South Korea' 'Hungary' 'Liechtenstein'
 'United States' 'Spain' 'China' 'United Arab Emirates' 'Canada' 'Macau'
 'Japan' 'Sweden' 'Luxembourg' 'Andorra' 'New Zealand' 'Norway'
 'Netherlands' 'Israel' 'Portugal' 'Poland' 'Moldova' 'Taiwan' 'Kuwait'
 'Lithuania' 'Malta' 'Panama' 'Germany' 'Latvia' 'Finland' 'Belgium'
 'Ireland' 'San Marino' 'Slovenia' 'Slovakia' 'Qatar' 'Brazil' 'Barbados'
 'Malaysia' 'Italy' 'United Kingdom' 'Russia' 'Saudi Arabia' 'Austria'
 'Estonia' 'Serbia' 'Bulgaria' 'Trinidad and Tobago' 'Jordan' 'Australia'
 'Vietnam' 'Ukraine' 'Bahrain' 'Paraguay' 'Colombia' 'Philippines'
 'Uruguay' 'Belarus' 'Croatia' 'Oman' 'Guyana' 'India' 'Kazakhstan'
 'Bahamas' 'Montenegro' 'Argentina' 'Peru' 'Grenada' 'Costa Rica' 'Cyprus'
 'Mexico' 'South Africa' 'Saint Vincent and the Grenadines' 'Mongolia'
 'Saint Lucia' 'Ghana' 'Kyrgyzstan' 'Bosnia and Herzegovina' 'Laos'
 'Uzbekistan' 'Al

In [55]:
dataset

country  broadband  mobile
0        103        174     135
1        141        173     118
2         64        172     108
3        129        171      89
4        152        170     125
..       ...        ...     ...
172       46          4     135
173      149          3       6
174      174          2     135
175      162          1     135
176       37          0      39

[177 rows x 3 columns]

In [56]:
x = data.drop(['country'], axis=1)
y = data['country']
y

0      103
1      141
2       64
3      129
4      152
      ... 
172     46
173    149
174    174
175    162
176     37
Name: country, Length: 177, dtype: int32

In [57]:
#Train test split 
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, 
                                                    random_state = 0)

In [58]:
#lihat jumlah data train & testing 
print(x_train.shape)
print(y_test.shape)

(132, 2)
(45,)


In [59]:
from sklearn.naive_bayes import GaussianNB 

model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [60]:
#pemodelan training
y_pred = model.predict(x_train)
y_pred
print(y_pred)

y_pred_test = model.predict(x_test)
print(y_pred_test)

[151   5  58 144  30 101  49 143 122 112  97 174  40 105  92 109 126  80
  95  43  31  53 125  64  12  99  57  23  65 113 124  60 140 120 139 106
  62 107   9  48 116  15  85  10  77 136 130  81 147  52 117  98  89 165
 145 138 155  38 129 162  69 157  66  35  21 173 167 158  86  33 103  73
 150  72  87  63 137  82 172 142  37  36 141 131  29 128 110   4  90  70
  68  25 108 171  55 102  20  88 176  84 119  96  78  18 115 154  74  56
 134  94 175   0   6 100  71 133  27   2 135 164 156 161  11   1  50   3
 146  41  61  45 166  46]
[172  18 125 130  85 171 130 119  99 133  27  29 141  99  29  80 130  90
  15   9  12 143 141  94  15  69  84  73  20  53 126  25  95  23  64 128
 119  41  43   0 151 117 155  41  20]


In [61]:
# y pred vs y actual

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_pred, y_train))

print(classification_report(y_pred, y_train))

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           9       1.00      1.00      1.00         1
          10       1.00      1.00      1.00         1
          11       1.00      1.00      1.00         1
          12       1.00      1.00      1.00         1
          15       1.00      1.00      1.00         1
          18       1.00      1.00      1.00         1
          20       1.00      1.00      1.00         1
          21       1.00      1.00      1.00         1
          23   

In [ ]:
#1.00 = 100% menandakan akurasi prediksi sebesar 100% dari data aslinya